contracts:
  - address: '0x097f8ae21e81d4f248a2e2d18543c6b3cc0d8e59'
    platform: BNB
crypto: true
fiat: false
id: APP
id_coinmarketcap: '14795'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/14795.png
logoKey: currencies/app.png
name: SappChat
