contracts:
  - address: '0x07150e919b4de5fd6a63de1f9384828396f25fdc'
    platform: ETH
crypto: true
fiat: false
id: BASE
id_coinmarketcap: '7838'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/7838.png
logoKey: currencies/base.png
name: Base Protocol
