crypto: true
fiat: false
id: BLOCKCHAINTOAPPLICATION
id_nomics: BLOCKCHAINTOAPPLICATION
logo: https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/BLOCKCHAINTOAPPLICATION.png
logoKey: currencies/blockchaintoapplication.png
name: Blockchain to application
platform: ETH
platform_contract: '0xd2bd6415db70a0f0b26c973b15b63bac74f5c9c6'
