contracts:
  - address: '0x57b59f981730c6257dF57cF6F0D98283749A9Eeb'
    platform: ETH
crypto: true
fiat: false
id: BUILD
id_coinmarketcap: '21113'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/21113.png
logoKey: currencies/build.png
name: BUILD
