contracts:
  - address: '0xEFF9CDb294872b6553F4E9631Fb4D1fa4F9C5e6B'
    platform: ETH
crypto: true
fiat: false
id: BUILD
id_coinmarketcap: '29514'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/29514.png
logoKey: currencies/build.png
name: BuildAI
