crypto: true
fiat: false
id: CHART
id_coinmarketcap: '6861'
id_coinpaprika: chart-chartex
id_nomics: CHART
logo: https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/CHART.jpg
logoKey: currencies/chart.jpg
name: ChartEx
platform: ETH
platform_contract: '0x1d37986f252d0e349522ea6c3b98cb935495e63e'
