contracts:
  - address: ASNoTS4cYopuUbmDMWM4AU9xdCQnb5zPe3gBWfTUsLTE
    platform: SOL
crypto: true
fiat: false
id: DEV
id_coinmarketcap: '33026'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/33026.png
logoKey: currencies/dev.png
name: My Dog Is The DEV
