crypto: true
fiat: false
id: DEV
id_coinmarketcap: '2649'
id_coinpaprika: dev-deviantcoin
id_nomics: DEV
logo: https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/DEV.png
logoKey: currencies/dev.png
name: Deviant Coin
