contracts:
  - address: r3Si5cWtHZZuKXQERoaTKc7Vhw53RdGi2A
    platform: XRP
crypto: true
fiat: false
id: GALAXY
id_coinmarketcap: '16687'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/16687.png
logoKey: currencies/galaxy.png
name: Galaxy Coin
