contracts:
  - address: terra1vchw83qt25j89zqwdpmdzj722sqxthnckqzxxp
    platform: LUNC
crypto: true
fiat: false
id: LOCAL
id_coinmarketcap: '18604'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/18604.png
name: Local Terra
