contracts:
  - address: '0x1afb69dbc9f54d08dab1bd3436f8da1af819e647'
    platform: ETH
crypto: true
fiat: false
id: MELOS
id_coinmarketcap: '18551'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/18551.png
logoKey: currencies/melos.png
name: Melos Studio
