crypto: true
fiat: false
id: MELOS
id_coinmarketcap: '18551'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/18551.png
name: Melos Studio
platform: ETH
platform_contract: '0x1afb69dbc9f54d08dab1bd3436f8da1af819e647'
