contracts:
  - address: '0xde2f7766c8bf14ca67193128535e5c7454f8387c'
    platform: ETH
crypto: true
fiat: false
id: META
id_coinmarketcap: '3418'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/3418.png
logoKey: currencies/meta.png
name: Metadium
