contracts:
  - address: '0x69A1e699f562D7Af66Fc6cc473d99f4430C3AcD2'
    platform: ETH
crypto: true
fiat: false
id: PARAM
id_coinmarketcap: '31311'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/31311.png
logoKey: currencies/param.png
name: Param
