crypto: true
fiat: false
id: PRODUCT
id_nomics: PRODUCT
logo: https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/PRODUCT.jpg
logoKey: currencies/product.jpg
name: Product
platform: MATIC
platform_contract: '0xa5f04aD400c61F3834d0bB581c17f2f7888d0199'
