contracts:
  - address: '0x6d110c53ba912da3bf9be792955f2ac578aa2d6b'
    platform: ETH
crypto: true
fiat: false
id: SECURITY
id_coinmarketcap: '26799'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/26799.png
logoKey: currencies/security.png
name: Security
