crypto: true
fiat: false
id: SMARTAPPLICATIONCHAIN
id_nomics: SMARTAPPLICATIONCHAIN
logo: https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/SMARTAPPLICATIONCHAIN.png
logoKey: currencies/smartapplicationchain.png
name: Smart Application Coin
platform: ETH
platform_contract: '0xabc1280a0187a2020cc675437aed400185f86db6'
