contracts:
  - address: '0x47474daeba9221034431656a89df46842f573770'
    platform: ETH
crypto: true
fiat: false
id: TRAIN1
id_coinmarketcap: '31857'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/31857.png
name: Trump Train
