crypto: true
fiat: false
id: TRAIN
id_coinmarketcap: '16438'
logo: https://s2.coinmarketcap.com/static/img/coins/64x64/16438.png
name: RailNode
platform: ETH
platform_contract: '0xA1a3c65a65FB09cD71aFF47E0C787E80cf501DD4'
