crypto: true
fiat: false
id: WEST
id_coinmarketcap: '5159'
id_coinpaprika: west-waves-enterprise
id_nomics: WEST
logo: https://s3.us-east-2.amazonaws.com/nomics-api/static/images/currencies/WEST.png
logoKey: currencies/west.png
name: Waves Enterprise
platform: WAVES
platform_contract: 4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8
